sudo: false
language: elixir
git:
  quiet: true
  depth: 3

matrix:
  include:
    - name: "Elixir 1.8.1 OTP 21.3.6"
      elixir: 1.8.1
      otp_release: 21.3.6
    - name: "Elixir 1.8.1 OTP 20.3.8"
      elixir: 1.8.1
      otp_release: 20.3.8
    - name: "Elixir 1.7.4 OTP 20.3.8"
      elixir: 1.7.4
      otp_release: 20.3.8
    - name: "Elixir 1.6.6 OTP 20.3.8"
      elixir: 1.6.6
      otp_release: 20.3.8

env:
  - MIX_ENV=test VERBOSE_TESTS=true
cache:
  directories:
    - _build
    - deps
before_script:
  - epmd -daemon
  - mix do deps.get, eqc.install --mini
script:
  - bin/travis
notifications:
  email:
    - paulschoenfelder@gmail.com
